spring.application.name=snake-identifier

server.port=8080
gemini.api.key=AIzaSyCjHlLi0GKlW7T6aYrBp0lciS3yUX91OVU
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB